# Generated by Django 5.0.3 on 2024-04-11 18:38

import Apps.DataVizLab.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataVizLab', '0002_csvfile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvfile',
            name='file',
            field=models.FileField(upload_to='uploads/', validators=[Apps.DataVizLab.models.validate_excel_file_extension]),
        ),
    ]
