# Generated by Django 5.0.3 on 2024-04-12 17:47

import Apps.DataVizLab.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataVizLab', '0003_alter_csvfile_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_file', models.BinaryField()),
                ('original_filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='', validators=[Apps.DataVizLab.models.validate_excel_file_extension])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CSVFile',
        ),
    ]
