# Generated by Django 5.0.3 on 2024-04-12 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataVizLab', '0004_excelfile_delete_csvfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='excelfile',
            name='encryption_key',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
