COMMON_COLUMNS = [
    "ID ",
    "Género",
    "Sociedad",
    "Provincia/ Zona",
    "Delegación/ CT",
    "Fecha de nacimiento",
    "Fecha de alta",
    "Nivel de estudios",
    "Depto/ Área",
    "Puesto",
    "Nivel PIV (IPE)",
    "Nivel PIV (IPE)",
    "Convenio de aplicación",
    "Comité de Dirección",
    "Representación de los trabajadores",
    "Programas de desarrollo (tipo)",
    "Tipo de contrato",
    "Tipo de jornada",
    "Régimen de trabajo a turnos",
    "% Jornada",
    "% Jornada reducida",
    "Motivo de jornada reducida",
    "Acuerdo Teletrabajo",
    "Estado Civil",
    "N. Personas Dependientes",
    "Fecha de corte",
]